name: flutter_fc
description: Writing Function Component in Flutter, just as writing in React.
version: 0.5.0
homepage: https://github.com/luo3house/flutter_fc

environment:
  sdk: '^3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
